server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/barahijawi/ea-spring-boot-config-server
          clone-on-start: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost/8762/eureka/
  instance:
    hostname: localhost