
spring:
  application:
    name: gateway

  zipkin:
    base-url: http://${ZIPKIN_SERVER:localhost}:9411

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER:localhost}:8761/eureka

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"

server:
  port: 8080