server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
spring:
#  main:
#    web-application-type: reactive
#    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  zipkin:
    base-url: http://localhost:9411
management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include:*
