spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER}:8090

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY}:8761/eureka/
