spring:
  application:
    name: ${APPLICATION_NAME:user-service}
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://locahost:8761/eureka
  datasource:
    url: ${spring.datasource.url:jdbc:postgresql://localhost:2222/ea-inclass-user-db}
    username: ${spring.datasource.username:postgres}
    password: ${spring.datasource.password:1}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  zipkin-base-url: ${ZIPKIN_URL:http://localhost:9411/zipkin/}

server:
  port: 8080

#management:
#  endpoints:
#    web:
#      exposure:
#        include:*
#    health:
#      show-details:always