server:
  port : 8761

eureka:
  client:
#    This is my Eureka Server, plaease don't register yourself in other server, and we should set them to true in client
    register-with-eureka: false
    fetch-registry: false
